# Generated by Django 6.0.3 on 2026-03-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpn',
            },
        ),
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('priorite_base', models.IntegerField(default=2)),
                ('longueur', models.FloatField()),
                ('tirant', models.FloatField()),
                ('arrivee', models.FloatField(help_text="Heure d'arrivée (format décimal)")),
                ('marchandise', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_limite', models.FloatField(blank=True, null=True)),
                ('etat', models.CharField(default='attente', max_length=20)),
            ],
            options={
                'db_table': 'navires',
            },
        ),
        migrations.CreateModel(
            name='Quai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('longueur', models.FloatField()),
                ('profondeur', models.FloatField()),
                ('specialite', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quais',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_accostage', models.FloatField()),
                ('attente', models.FloatField()),
                ('priorite_calculee', models.FloatField()),
                ('cpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='port.cpn')),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.quai')),
            ],
            options={
                'db_table': 'affectations',
            },
        ),
        migrations.CreateModel(
            name='TempsTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.FloatField(help_text='Temps de traitement en heures')),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.quai')),
            ],
            options={
                'db_table': 'temps_traitement',
                'unique_together': {('quai', 'navire')},
            },
        ),
    ]
