# Generated by Django 6.0.3 on 2026-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='duree_traitement',
            field=models.FloatField(default=10),
        ),
    ]
