# Generated by Django 6.0.3 on 2026-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_navire_duree_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='convention_speciale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navire',
            name='est_passage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navire',
            name='est_sortant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navire',
            name='strategique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navire',
            name='etat',
            field=models.CharField(choices=[('attente', 'En attente'), ('planifie', 'Planifié'), ('historique', 'Historique')], default='attente', max_length=20),
        ),
    ]
