# Generated by Django 6.0.3 on 2026-03-14 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_navire_convention_speciale_navire_est_passage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.FloatField(help_text='Capacité en tonnes')),
                ('nombre', models.IntegerField(help_text='Nombre total disponible')),
                ('disponibles', models.IntegerField(help_text='Nombre actuellement disponible')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='SessionOptimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_navires', models.IntegerField()),
                ('nb_quais', models.IntegerField()),
                ('score_total', models.FloatField()),
                ('attente_totale', models.FloatField()),
                ('attente_moyenne', models.FloatField()),
                ('taux_occupation', models.FloatField()),
                ('saison', models.CharField(choices=[('hiver', 'Hiver'), ('ete', 'Été')], max_length=10)),
                ('fichier_csv', models.CharField(blank=True, help_text='Chemin du fichier CSV exporté', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='cpn',
        ),
        migrations.AlterUniqueTogether(
            name='tempstraitement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tempstraitement',
            name='navire',
        ),
        migrations.RemoveField(
            model_name='tempstraitement',
            name='quai',
        ),
        migrations.AlterModelOptions(
            name='navire',
            options={'verbose_name': 'Navire', 'verbose_name_plural': 'Navires'},
        ),
        migrations.AlterModelOptions(
            name='quai',
            options={'verbose_name': 'Quai', 'verbose_name_plural': 'Quais'},
        ),
        migrations.RenameField(
            model_name='affectation',
            old_name='heure_accostage',
            new_name='heure_debut',
        ),
        migrations.RenameField(
            model_name='affectation',
            old_name='priorite_calculee',
            new_name='heure_fin',
        ),
        migrations.RenameField(
            model_name='navire',
            old_name='convention_speciale',
            new_name='marchandise_dangereuse',
        ),
        migrations.RenameField(
            model_name='navire',
            old_name='est_passage',
            new_name='marchandise_frigo',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='duree_limite',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='duree_traitement',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='est_sortant',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='marchandise',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='priorite_base',
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='affectation',
            name='equipements',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=200),
        ),
        migrations.AddField(
            model_name='affectation',
            name='priorites_texte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='affectation',
            name='score_contribution',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affectation',
            name='traitement',
            field=models.FloatField(default=0.0, help_text='Temps de traitement en heures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affectation',
            name='utilise_grues_bord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navire',
            name='a_grue_bord',
            field=models.BooleanField(default=False, help_text='Navire équipé de ses propres grues'),
        ),
        migrations.AddField(
            model_name='navire',
            name='animalier',
            field=models.BooleanField(default=False, help_text='Animalier'),
        ),
        migrations.AddField(
            model_name='navire',
            name='convention',
            field=models.BooleanField(default=False, help_text='Convention spéciale'),
        ),
        migrations.AddField(
            model_name='navire',
            name='essence',
            field=models.BooleanField(default=False, help_text='Caboteur essence'),
        ),
        migrations.AddField(
            model_name='navire',
            name='gazier',
            field=models.BooleanField(default=False, help_text='Gazier'),
        ),
        migrations.AddField(
            model_name='navire',
            name='grue_capacite',
            field=models.FloatField(default=0, help_text='Capacité des grues de bord (tonnes)'),
        ),
        migrations.AddField(
            model_name='navire',
            name='heure_debut',
            field=models.FloatField(blank=True, help_text="Heure de début d'accostage", null=True),
        ),
        migrations.AddField(
            model_name='navire',
            name='heure_fin',
            field=models.FloatField(blank=True, help_text="Heure de fin d'accostage", null=True),
        ),
        migrations.AddField(
            model_name='navire',
            name='huilier',
            field=models.BooleanField(default=False, help_text='Huilier'),
        ),
        migrations.AddField(
            model_name='navire',
            name='ligne_reguliere',
            field=models.BooleanField(default=False, help_text='Ligne régulière (ferry)'),
        ),
        migrations.AddField(
            model_name='navire',
            name='marchandise_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='navire',
            name='marchandise_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='navire',
            name='passage',
            field=models.BooleanField(default=False, help_text='Navire de passage'),
        ),
        migrations.AddField(
            model_name='navire',
            name='perissable',
            field=models.BooleanField(default=False, help_text='Denrées périssables'),
        ),
        migrations.AddField(
            model_name='navire',
            name='priorite_calculee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='navire',
            name='quai_attribue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.quai'),
        ),
        migrations.AddField(
            model_name='navire',
            name='sortant',
            field=models.BooleanField(default=False, help_text='Navire sortant'),
        ),
        migrations.AddField(
            model_name='quai',
            name='occupation_jusqua',
            field=models.FloatField(default=0.0, help_text='Heure de libération'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='attente',
            field=models.FloatField(help_text="Temps d'attente en heures"),
        ),
        migrations.AlterField(
            model_name='navire',
            name='etat',
            field=models.CharField(choices=[('attente', '⏳ En attente'), ('rade', '⚓ En rade'), ('quai', '🚢 À quai'), ('termine', '✅ Terminé')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='navire',
            name='longueur',
            field=models.FloatField(help_text='Longueur en mètres'),
        ),
        migrations.AlterField(
            model_name='navire',
            name='strategique',
            field=models.BooleanField(default=False, help_text='Produit stratégique'),
        ),
        migrations.AlterField(
            model_name='navire',
            name='tirant',
            field=models.FloatField(help_text="Tirant d'eau en mètres"),
        ),
        migrations.AlterField(
            model_name='navire',
            name='type',
            field=models.CharField(choices=[('conteneur', 'Conteneur'), ('cerealier', 'Céréalier'), ('ferry', 'Ferry'), ('gazier', 'Gazier'), ('frigorifique', 'Frigorifique'), ('betail', 'Bétail'), ('essence', 'Essence'), ('huilier', 'Huilier'), ('petrolier', 'Pétrolier'), ('cargo', 'Cargo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quai',
            name='longueur',
            field=models.FloatField(help_text='Longueur en mètres'),
        ),
        migrations.AlterField(
            model_name='quai',
            name='profondeur',
            field=models.FloatField(help_text='Profondeur en mètres'),
        ),
        migrations.AlterField(
            model_name='quai',
            name='specialite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='affectation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='navire',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quai',
            table=None,
        ),
        migrations.DeleteModel(
            name='CPN',
        ),
        migrations.DeleteModel(
            name='TempsTraitement',
        ),
    ]
