# Generated by Django 6.0.3 on 2026-03-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_equipement_sessionoptimisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='navire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quai',
            options={},
        ),
    ]
