# Generated by Django 6.0.3 on 2026-03-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_alter_equipement_options_alter_navire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='pret_pour_quai',
            field=models.BooleanField(default=True, help_text='Navire prêt pour affectation'),
        ),
    ]
