# Generated by Django 6.0.3 on 2026-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_navire_pret_pour_quai'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='equipements_utilises',
            field=models.TextField(blank=True, help_text='Liste des équipements utilisés'),
        ),
    ]
