# Generated by Django 6.0.3 on 2026-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_affectation_equipements_utilises'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='equipements_utilises_ids',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=500),
        ),
    ]
