# Generated by Django 6.0.3 on 2026-03-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_affectation_equipements_utilises_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='date_debut_reel',
            field=models.DateTimeField(blank=True, help_text='Date et heure réelle de début', null=True),
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_fin_reel',
            field=models.DateTimeField(blank=True, help_text='Date et heure réelle de fin', null=True),
        ),
    ]
