# Generated by Django 6.0.3 on 2026-03-24 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0009_affectation_date_debut_reel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='attente',
            field=models.FloatField(help_text="Temps d'attente en heures", verbose_name='Attente'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_debut_reel',
            field=models.DateTimeField(blank=True, help_text='Date et heure réelle de début', null=True, verbose_name='Date début réelle'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_fin_reel',
            field=models.DateTimeField(blank=True, help_text='Date et heure réelle de fin', null=True, verbose_name='Date fin réelle'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=200, verbose_name='Équipements'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements_utilises',
            field=models.TextField(blank=True, help_text='Liste des équipements utilisés', verbose_name='Équipements utilisés'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements_utilises_ids',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=500, verbose_name='IDs équipements'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='heure_debut',
            field=models.FloatField(verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='heure_fin',
            field=models.FloatField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='priorites_texte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Priorités'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='score_contribution',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='traitement',
            field=models.FloatField(help_text='Temps de traitement en heures', verbose_name='Traitement'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='utilise_grues_bord',
            field=models.BooleanField(default=False, verbose_name='Grues de bord'),
        ),
    ]
