# Generated by Django 6.0.3 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0010_alter_affectation_attente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='pret_par_client',
            field=models.BooleanField(default=False, help_text='Le client a confirmé que le navire est prêt à accoster'),
        ),
    ]
