# Generated by Django 6.0.3 on 2026-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_navire_pret_par_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='en_panne',
            field=models.BooleanField(default=False, help_text='En panne actuellement ?'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='temps_reparation',
            field=models.FloatField(default=2.0, help_text='Temps de réparation estimé (heures)'),
        ),
    ]
