# Generated by Django 6.0.3 on 2026-03-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0012_equipement_en_panne_equipement_temps_reparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etat', models.CharField(choices=[('attente', '⏳ En attente'), ('rade', '⚓ En rade'), ('quai', '🚢 À quai'), ('termine', '✅ Terminé')], max_length=20)),
                ('arrivee', models.FloatField()),
                ('heure_debut', models.FloatField(blank=True, null=True)),
                ('heure_fin', models.FloatField(blank=True, null=True)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('quai_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.quai')),
            ],
            options={
                'ordering': ['-date', 'navire__nom'],
                'unique_together': {('date', 'navire')},
            },
        ),
    ]
