# Generated by Django 6.0.3 on 2026-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_snapshotnavire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshotnavire',
            options={},
        ),
        migrations.AddField(
            model_name='navire',
            name='arrivee_datetime',
            field=models.DateTimeField(blank=True, help_text="Date et heure réelle d'arrivée en rade", null=True),
        ),
    ]
