# Generated by Django 6.0.3 on 2026-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0014_alter_snapshotnavire_options_navire_arrivee_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='debut_datetime',
            field=models.DateTimeField(blank=True, help_text='Date et heure réelle de début à quai', null=True),
        ),
    ]
