# Generated by Django 6.0.3 on 2026-03-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_navire_debut_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='quai',
            name='performance',
            field=models.FloatField(default=1.0, help_text='Coefficient multiplicateur de cadence (1.0 = standard)'),
        ),
    ]
