# Generated by Django 6.0.3 on 2026-03-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_quai_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='buffer_debut',
            field=models.FloatField(default=0, verbose_name='Buffer début (h)'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='buffer_fin',
            field=models.FloatField(default=0, verbose_name='Buffer fin (h)'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='heure_debut_reel',
            field=models.FloatField(blank=True, null=True, verbose_name='Début réel (avec buffer)'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='heure_fin_reel',
            field=models.FloatField(blank=True, null=True, verbose_name='Fin réelle (avec buffer)'),
        ),
    ]
