# Generated by Django 6.0.3 on 2026-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_affectation_buffer_debut_affectation_buffer_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='coeff_variation',
            field=models.FloatField(default=0.15, help_text='Coefficient de variation pour la durée'),
        ),
        migrations.AlterField(
            model_name='quai',
            name='performance',
            field=models.FloatField(default=1.0, help_text='Coefficient multiplicateur de cadence'),
        ),
    ]
