# Generated by Django 6.0.3 on 2026-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_navire_coeff_variation_alter_quai_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
