# Generated by Django 6.0.3 on 2026-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_alter_equipement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='etat_initial',
            field=models.CharField(blank=True, choices=[('attente', '⏳ En attente'), ('rade', '⚓ En rade'), ('quai', '🚢 À quai'), ('termine', '✅ Terminé')], max_length=20, null=True, verbose_name='État initial'),
        ),
    ]
