# Generated by Django 6.0.3 on 2026-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0020_affectation_etat_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionoptimisation',
            name='amplitude_pct',
            field=models.FloatField(default=20, verbose_name='Amplitude (%)'),
        ),
        migrations.AddField(
            model_name='sessionoptimisation',
            name='buffer_pct',
            field=models.FloatField(default=15, verbose_name='Buffer (%)'),
        ),
        migrations.AddField(
            model_name='sessionoptimisation',
            name='incertitude_utilisee',
            field=models.BooleanField(default=False, verbose_name='Incertitude activée'),
        ),
    ]
