# Generated by Django 6.0.3 on 2026-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0021_sessionoptimisation_amplitude_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='panne_debut',
            field=models.DateTimeField(blank=True, help_text='Début de la panne', null=True),
        ),
    ]
