# Generated by Django 6.0.3 on 2026-04-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0022_equipement_panne_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('vent_force', models.IntegerField(default=0)),
                ('hauteur_houle', models.FloatField(default=0)),
                ('restrictions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
