# Generated by Django 6.0.3 on 2026-04-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0023_meteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='vent_direction',
            field=models.CharField(blank=True, help_text='Ex: N, NE, E, SE, S, SO, O, NO', max_length=10),
        ),
    ]
