# Generated by Django 6.0.3 on 2026-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0024_meteo_vent_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='description',
            field=models.CharField(blank=True, help_text='Description météo', max_length=100),
        ),
        migrations.AddField(
            model_name='meteo',
            name='pluie',
            field=models.BooleanField(default=False, help_text='Pluie en cours'),
        ),
        migrations.AddField(
            model_name='meteo',
            name='precipitation',
            field=models.FloatField(default=0, help_text='Quantité de précipitations (mm/h)'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Quais interdits (séparés par des virgules)'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_direction',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
