# Generated by Django 6.0.3 on 2026-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0025_meteo_description_meteo_pluie_meteo_precipitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='temperature',
            field=models.FloatField(default=20, help_text='Température en degrés Celsius'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='hauteur_houle',
            field=models.FloatField(default=0, help_text='Hauteur de la houle en mètres'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_direction',
            field=models.CharField(blank=True, help_text='Direction du vent (N, NE, E, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_force',
            field=models.IntegerField(default=0, help_text='Force du vent (Beaufort)'),
        ),
    ]
