# Generated by Django 6.0.3 on 2026-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0026_meteo_temperature_alter_meteo_hauteur_houle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionoptimisation',
            name='scenario',
            field=models.CharField(choices=[('rapide', 'Rapide'), ('equilibre', 'Équilibré'), ('securise', 'Sécurisé')], default='equilibre', max_length=20, verbose_name="Scénario d'optimisation"),
        ),
    ]
