# Generated by Django 6.0.3 on 2026-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0027_sessionoptimisation_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navire_type', models.CharField(max_length=20)),
                ('quai_id', models.IntegerField()),
                ('volume', models.FloatField()),
                ('duree_estimee', models.FloatField(help_text='Durée estimée avant traitement (heures)')),
                ('duree_reelle', models.FloatField(help_text='Durée réelle observée (heures)')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['navire_type', 'quai_id'], name='port_histor_navire__55a359_idx')],
            },
        ),
    ]
