# Generated by Django 6.0.3 on 2026-04-03 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0028_historiqueoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conflit_quai', 'Conflit de quai'), ('manque_equipement', "Manque d'équipement"), ('navire_critique', 'Navire critique en attente'), ('retard', 'Retard important'), ('meteo', 'Condition météo dangereuse')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'ℹ️ Information'), ('warning', '⚠️ Attention'), ('danger', '🔴 Critique')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, help_text="URL pour résoudre l'alerte", max_length=200)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
