# Generated by Django 6.0.3 on 2026-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0029_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='quai',
            name='bloque',
            field=models.BooleanField(default=False, help_text='Quai bloqué manuellement (indisponible)'),
        ),
    ]
