# Generated by Django 6.0.3 on 2026-04-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0030_quai_bloque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navire',
            options={'permissions': [('can_manage_cpn', 'Peut gérer la CPN'), ('can_optimize', "Peut lancer l'optimisation"), ('can_export', 'Peut exporter les plannings'), ('can_finish_ships', 'Peut terminer des navires'), ('can_validate_arrival', "Peut valider l'arrivée en rade"), ('can_execute_decision', 'Peut exécuter une décision'), ('can_edit_ship', 'Peut modifier un navire'), ('can_load_announcements', 'Peut charger les annonces'), ('can_manage_users', 'Peut gérer les utilisateurs'), ('can_view_user_logs', "Peut consulter l'historique des tâches")]},
        ),
    ]
