# Generated by Django 6.0.3 on 2026-04-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0031_alter_navire_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quai',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
