# Generated by Django 6.0.3 on 2026-04-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0032_alter_quai_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_prevue', models.FloatField(help_text='Heure à laquelle effectuer le mouvement')),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('prevue', 'Prévue'), ('executee', 'Exécutée')], default='prevue', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ancien_quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='port.quai')),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('nouveau_quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='port.quai')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
