# Generated by Django 6.0.3 on 2026-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0033_alter_equipement_type_mouvement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerte',
            options={},
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
