# Generated by Django 6.0.3 on 2026-04-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0035_equipement_latitude_equipement_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='coord_x',
            field=models.FloatField(blank=True, help_text='Position X sur le plan', null=True),
        ),
        migrations.AddField(
            model_name='navire',
            name='coord_y',
            field=models.FloatField(blank=True, help_text='Position Y sur le plan', null=True),
        ),
        migrations.AddField(
            model_name='quai',
            name='coord_x',
            field=models.FloatField(blank=True, help_text='Coordonnée X sur le plan (mètres ou pixels)', null=True),
        ),
        migrations.AddField(
            model_name='quai',
            name='coord_y',
            field=models.FloatField(blank=True, help_text='Coordonnée Y sur le plan', null=True),
        ),
    ]
