# Generated by Django 6.0.3 on 2026-04-12 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0036_navire_coord_x_navire_coord_y_quai_coord_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='quai',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='quai',
            name='longitude',
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('affectation', 'Affectation de navire'), ('deplacement', 'Déplacement manuel'), ('priorite', 'Forçage de priorité'), ('blocage_quai', 'Blocage/Déblocage de quai'), ('terminaison', 'Terminaison de navire'), ('modification', 'Modification (CRUD)'), ('arrivee_rade', 'Validation arrivée rade')], max_length=30)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.equipement')),
                ('navire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.navire')),
                ('quai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.quai')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historiques des actions',
                'ordering': ['-date_action'],
            },
        ),
    ]
