# Generated by Django 6.0.3 on 2026-04-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0037_remove_equipement_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, help_text='Matricule EPB', max_length=20, null=True, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste / Fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
