# Generated by Django 6.0.3 on 2026-04-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0038_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MSC', 'MSC'), ('CMA_CGM', 'CMA CGM'), ('MAERSK', 'Maersk')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_jours', models.IntegerField(default=4, help_text='Durée prévue en jours')),
                ('actif', models.BooleanField(default=True)),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.quai')),
            ],
            options={
                'verbose_name': 'Créneau réservé',
                'verbose_name_plural': 'Créneaux réservés',
            },
        ),
    ]
