# Generated by Django 6.0.3 on 2026-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0039_creneaureserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='agent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agent / Consignataire'),
        ),
    ]
