# Generated by Django 6.0.3 on 2026-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0040_navire_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quai',
            name='coeff_manoeuvre',
            field=models.FloatField(default=1.0, help_text='Coefficient multiplicateur du temps de manœuvre (1.0 = référence)'),
        ),
    ]
