# Generated by Django 6.0.3 on 2026-04-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0041_quai_coeff_manoeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='quai',
            name='capacite_max',
            field=models.FloatField(default=0, help_text="Capacité maximale d'accueil en tonnes (0 = illimitée)"),
        ),
    ]
