# Generated by Django 6.0.3 on 2026-04-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0042_quai_capacite_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='quai',
            name='type_navire_autorise',
            field=models.CharField(blank=True, help_text='Types de navires autorisés (détail)', max_length=200),
        ),
    ]
