# Generated by Django 6.0.3 on 2026-04-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0043_quai_type_navire_autorise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro du poste (ex: 01, 02, etc.)', max_length=10)),
                ('longueur', models.FloatField(help_text='Longueur en mètres')),
                ('profondeur', models.FloatField(help_text='Profondeur en mètres')),
                ('specialite', models.CharField(blank=True, help_text='Spécialité du poste', max_length=50)),
                ('type_navire_autorise', models.CharField(blank=True, help_text='Types de navires autorisés', max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('occupation_jusqua', models.FloatField(default=0.0, help_text='Heure de libération')),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='port.quai')),
            ],
        ),
    ]
