# Generated by Django 6.0.3 on 2026-04-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0044_poste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneaureserve',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'verbose_name': 'Créneau réservé', 'verbose_name_plural': 'Créneaux réservés'},
        ),
    ]
