# Generated by Django 6.0.3 on 2026-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0045_alter_creneaureserve_options_alter_poste_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneaureserve',
            options={'verbose_name': 'Créneau réservé', 'verbose_name_plural': 'Créneaux réservés'},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={},
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
