# Generated by Django 6.0.3 on 2026-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0046_alter_creneaureserve_options_alter_poste_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='gestion_manuelle',
            field=models.BooleanField(default=False, help_text="Si True, ce poste n'est pas géré par l'optimiseur automatique"),
        ),
    ]
