# Generated by Django 6.0.3 on 2026-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0047_poste_gestion_manuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='entite',
            field=models.CharField(blank=True, choices=[('EPB', 'EPB'), ('BMT', 'BMT'), ('CEVITAL', 'Cevital/COGB'), ('NAFTAL', 'NAFTAL'), ('STH', 'STH'), ('OAIC', 'OAIC')], max_length=20, verbose_name='Entité exploitante'),
        ),
    ]
