# Generated by Django 6.0.3 on 2026-04-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0048_navire_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('shifts_couverts', models.CharField(help_text='Ex: 07h-13h,13h-19h', max_length=100)),
                ('repos_min_heures', models.FloatField(default=8.0)),
                ('max_heures_par_jour', models.FloatField(default=12.0)),
                ('debut_journee', models.FloatField(default=7.0)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_heures', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.equipe')),
            ],
            options={
                'unique_together': {('equipe', 'navire', 'shift', 'date_debut')},
            },
        ),
    ]
