# Generated by Django 6.0.3 on 2026-04-18 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0049_equipe_affectationequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.poste'),
        ),
    ]
