# Generated by Django 6.0.3 on 2026-04-18 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0050_affectation_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='poste_attribue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navires', to='port.poste'),
        ),
    ]
