# Generated by Django 6.0.3 on 2026-04-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0051_navire_poste_attribue'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='fin_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
