# Generated by Django 6.0.3 on 2026-04-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0052_navire_fin_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipement',
            options={'ordering': ['categorie', 'designation']},
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='disponibles',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='en_panne',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='panne_debut',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='type',
        ),
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(choices=[('engin', 'Engins (chariots, tracteurs, pelles, chargeurs)'), ('grue', 'Grues et portiques')], default='engin', max_length=10),
        ),
        migrations.AddField(
            model_name='equipement',
            name='designation',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipement',
            name='engins_en_marche',
            field=models.PositiveIntegerField(default=0, verbose_name='Engins en marche'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='engins_en_panne',
            field=models.PositiveIntegerField(default=0, verbose_name='Engins en panne'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='engins_existants',
            field=models.PositiveIntegerField(default=0, verbose_name='Engins existants'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='capacite',
            field=models.FloatField(default=0, verbose_name='Capacité (tonnes)'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='temps_reparation',
            field=models.FloatField(default=2.0, verbose_name='Temps réparation (h)'),
        ),
    ]
