# Generated by Django 6.0.3 on 2026-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0053_alter_equipement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='capacite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capacité / Type'),
        ),
    ]
