# Generated by Django 6.0.3 on 2026-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0054_alter_equipement_capacite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipement',
            options={},
        ),
        migrations.AlterField(
            model_name='equipement',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='equipement',
            unique_together={('categorie', 'designation', 'capacite')},
        ),
    ]
