# Generated by Django 6.0.3 on 2026-04-20 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0055_alter_equipement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EffectifShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metier', models.CharField(max_length=50)),
                ('affectes', models.PositiveIntegerField(default=0)),
                ('presents', models.PositiveIntegerField(default=0)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectifs', to='port.shift')),
            ],
            options={
                'unique_together': {('shift', 'metier')},
            },
        ),
    ]
