# Generated by Django 6.0.3 on 2026-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0056_shift_effectifshift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effectifshift',
            old_name='affectes',
            new_name='effectifs_affectes',
        ),
        migrations.RenameField(
            model_name='effectifshift',
            old_name='presents',
            new_name='effectifs_presents',
        ),
        migrations.AlterField(
            model_name='effectifshift',
            name='metier',
            field=models.CharField(max_length=30),
        ),
    ]
