# Generated by Django 6.0.3 on 2026-04-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0057_rename_affectes_effectifshift_effectifs_affectes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement_type', models.CharField(max_length=50)),
                ('unite_index', models.PositiveSmallIntegerField()),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('conflit', models.BooleanField(default=False)),
                ('attente_navire', models.FloatField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.quai')),
            ],
        ),
    ]
