# Generated by Django 6.0.3 on 2026-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0058_utilisationequipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueoperation',
            name='debit_reel',
            field=models.FloatField(default=0.0, help_text='Tonnage par heure réel'),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='equipements_utilises',
            field=models.TextField(blank=True, help_text='Liste des équipements (noms)'),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='nb_equipes',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre d'équipes ayant travaillé"),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='shift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
