# Generated by Django 6.0.3 on 2026-04-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0059_historiqueoperation_debit_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueoperation',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.poste'),
        ),
    ]
