# Generated by Django 6.0.3 on 2026-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0060_historiqueoperation_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='nb_equipes_requises',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Nombre d'équipes nécessaires"),
        ),
        migrations.AddField(
            model_name='navire',
            name='shift_requis',
            field=models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir'), ('nuit', 'Nuit')], default='matin', max_length=10, verbose_name='Shift requis'),
        ),
    ]
