# Generated by Django 6.0.3 on 2026-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0061_navire_nb_equipes_requises_navire_shift_requis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueoperation',
            name='attente_shift',
            field=models.FloatField(default=0.0, help_text="Temps d'attente (camions, etc.) pendant ce shift"),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='debit_shift',
            field=models.FloatField(default=0.0, help_text='Débit réel pendant ce shift (tonnes/heure effective)'),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='nb_equipements_utilises',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre d'équipements actifs pendant ce shift"),
        ),
        migrations.AddField(
            model_name='historiqueoperation',
            name='tonnage_shift',
            field=models.FloatField(default=0.0, help_text='Tonnage déchargé pendant ce shift'),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='shift',
            field=models.CharField(blank=True, choices=[('matin', 'Matin'), ('soir', 'Soir'), ('nuit', 'Nuit'), ('double_nuit', 'Double nuit')], max_length=12, null=True),
        ),
    ]
