# Generated by Django 6.0.3 on 2026-04-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0062_historiqueoperation_attente_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Équipement concerné')),
                ('shift', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir'), ('nuit', 'Nuit'), ('double_nuit', 'Double nuit')], max_length=12, verbose_name='Shift concerné')),
                ('duree_attente', models.FloatField(verbose_name="Durée de l'attente (heures)")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('prise_en_compte', models.BooleanField(default=False, verbose_name='Prise en compte dans la planification')),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_attente', to='port.navire')),
            ],
            options={
                'verbose_name': "Note d'attente",
                'verbose_name_plural': "Notes d'attente",
                'ordering': ['-date_creation'],
            },
        ),
    ]
