# Generated by Django 6.0.3 on 2026-04-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0063_noteattente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteattente',
            options={},
        ),
        migrations.RemoveField(
            model_name='noteattente',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='noteattente',
            name='prise_en_compte',
        ),
        migrations.RemoveField(
            model_name='noteattente',
            name='shift',
        ),
        migrations.AddField(
            model_name='noteattente',
            name='traitee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='duree_attente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='navire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire'),
        ),
    ]
