# Generated by Django 6.0.3 on 2026-04-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0064_alter_noteattente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteattente',
            old_name='traitee',
            new_name='prise_en_compte',
        ),
        migrations.AddField(
            model_name='noteattente',
            name='shift',
            field=models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir'), ('nuit', 'Nuit'), ('double_nuit', 'Double nuit')], default='matin', max_length=20),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='duree_attente',
            field=models.FloatField(help_text="Durée de l'attente en heures"),
        ),
    ]
