# Generated by Django 6.0.3 on 2026-04-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0065_rename_traitee_noteattente_prise_en_compte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteattente',
            name='duree_attente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='noteattente',
            name='shift',
            field=models.CharField(blank=True, choices=[('matin', 'Matin'), ('soir', 'Soir'), ('nuit', 'Nuit'), ('double_nuit', 'Double nuit')], max_length=20, null=True),
        ),
    ]
