# Generated by Django 6.0.3 on 2026-04-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0066_alter_noteattente_duree_attente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationQuai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_navire', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
                ('longueur', models.FloatField()),
                ('tirant', models.FloatField()),
                ('agent', models.CharField(blank=True, max_length=100)),
                ('entite', models.CharField(blank=True, max_length=20)),
                ('shift_debut', models.CharField(blank=True, max_length=10)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='port.poste')),
                ('quai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.quai')),
            ],
        ),
    ]
