# Generated by Django 6.0.3 on 2026-04-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0067_affectationquai'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='famille',
            field=models.CharField(blank=True, help_text="Famille d'équipement", max_length=50),
        ),
    ]
