# Generated by Django 6.0.3 on 2026-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0068_equipement_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, help_text='Catégorie fonctionnelle (ex: grue_mobile_50t)', max_length=50),
        ),
    ]
