# Generated by Django 6.0.3 on 2026-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0069_alter_equipement_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='pret_consignataire',
            field=models.BooleanField(default=False, verbose_name='Prêt pour le port (validé par le consignataire)'),
        ),
    ]
