# Generated by Django 6.0.3 on 2026-04-27 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0070_navire_pret_consignataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='etat_precedent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NotificationConsignataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Alerte'), ('success', 'Succès')], default='info', max_length=10)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consignataire', models.ForeignKey(limit_choices_to={'groups__name': 'Consignataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.navire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
