# Generated by Django 6.0.3 on 2026-04-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0071_navire_etat_precedent_notificationconsignataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconsignataire',
            name='consignataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationconsignataire',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Alerte'), ('success', 'Succès'), ('danger', 'Urgent')], default='info', max_length=10),
        ),
    ]
