# Generated by Django 6.0.3 on 2026-04-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0072_alter_notificationconsignataire_consignataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='source',
            field=models.CharField(default='Système', max_length=50),
        ),
    ]
