# Generated by Django 6.0.3 on 2026-04-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0073_alerte_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='pluie_fin_prevue',
            field=models.DateTimeField(blank=True, help_text='Prévision de fin de la pluie', null=True),
        ),
    ]
