# Generated by Django 6.0.3 on 2026-04-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0074_meteo_pluie_fin_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='pluie_debut_prevue',
            field=models.DateTimeField(blank=True, help_text='Début prévu de la pluie', null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='pluie_fin_prevue',
            field=models.DateTimeField(blank=True, help_text='Fin prévue de la pluie', null=True),
        ),
    ]
