# Generated by Django 6.0.3 on 2026-04-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0075_meteo_pluie_debut_prevue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='pluie_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meteo',
            name='pluie_debut_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='navire',
            name='temps_arret_pluie',
            field=models.FloatField(default=0.0),
        ),
    ]
