# Generated by Django 6.0.3 on 2026-09-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0076_meteo_pluie_active_meteo_pluie_debut_reelle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteattente',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='creneaureserve',
            name='poste',
            field=models.ForeignKey(blank=True, help_text='Poste spécifique (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.poste'),
        ),
        migrations.AddField(
            model_name='noteattente',
            name='archive',
            field=models.BooleanField(default=False, help_text="True si l'escale est terminée (utilisée pour l'IA)"),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_debut_reel',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date début réelle'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_fin_reel',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date fin réelle'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=200),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements_utilises',
            field=models.TextField(blank=True, help_text='Liste des équipements utilisés'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='equipements_utilises_ids',
            field=models.CharField(blank=True, help_text='IDs des équipements utilisés', max_length=500),
        ),
        migrations.AlterField(
            model_name='creneaureserve',
            name='duree_jours',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, help_text='Catégorie fonctionnelle', max_length=50),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('affectation', 'Affectation de navire'), ('deplacement', 'Déplacement manuel'), ('priorite', 'Forçage de priorité'), ('blocage_quai', 'Blocage/Déblocage de quai'), ('terminaison', 'Terminaison de navire'), ('modification', 'Modification (CRUD)'), ('arrivee_rade', 'Validation arrivée rade'), ('affectation_manuelle', 'Affectation manuelle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='attente_shift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='debit_shift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='equipements_utilises',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='nb_equipements_utilises',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='nb_equipes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historiqueoperation',
            name='tonnage_shift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='pluie_debut_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='pluie_fin_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='precipitation',
            field=models.FloatField(default=0, help_text='Précipitations (mm/h)'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Quais interdits (séparés par virgules)'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='temperature',
            field=models.FloatField(default=20, help_text='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_direction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='navire',
            name='pret_consignataire',
            field=models.BooleanField(default=False, verbose_name='Prêt pour le port'),
        ),
        migrations.AlterField(
            model_name='navire',
            name='pret_par_client',
            field=models.BooleanField(default=False, help_text='Le client a confirmé que le navire est prêt'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='gestion_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poste',
            name='numero',
            field=models.CharField(help_text='Numéro du poste', max_length=10),
        ),
        migrations.AlterField(
            model_name='poste',
            name='occupation_jusqua',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='poste',
            name='specialite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poste',
            name='type_navire_autorise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quai',
            name='coeff_manoeuvre',
            field=models.FloatField(default=1.0, help_text='Coefficient multiplicateur du temps de manœuvre'),
        ),
        migrations.AlterField(
            model_name='quai',
            name='coord_x',
            field=models.FloatField(blank=True, help_text='Coordonnée X sur le plan', null=True),
        ),
        migrations.AlterField(
            model_name='quai',
            name='type_navire_autorise',
            field=models.CharField(blank=True, help_text='Types de navires autorisés', max_length=200),
        ),
        migrations.AlterField(
            model_name='sessionoptimisation',
            name='fichier_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text="True si l'escale est en cours")),
                ('attente_totale', models.FloatField(default=0.0, help_text='Attente cumulée (h)')),
                ('traitement_total', models.FloatField(default=0.0, help_text='Traitement total (h)')),
                ('meteo_pluie', models.BooleanField(default=False)),
                ('meteo_vent_force', models.IntegerField(default=0)),
                ('volume_marchandise', models.FloatField(default=0.0)),
                ('duree_reelle', models.FloatField(default=0.0, help_text='Durée réelle totale (h)')),
                ('debit_reel', models.FloatField(default=0.0, help_text='Débit réel (t/h)')),
                ('agent', models.CharField(blank=True, max_length=100)),
                ('type_navire', models.CharField(blank=True, max_length=20)),
                ('shift_debut', models.CharField(blank=True, max_length=20)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escales', to='port.navire')),
                ('poste_utilise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escales_utilisees', to='port.poste')),
                ('quai_utilise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escales_utilisees', to='port.quai')),
            ],
            options={
                'verbose_name': 'Escale',
                'verbose_name_plural': 'Escales',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='noteattente',
            name='escale',
            field=models.ForeignKey(blank=True, help_text='Escale associée (None = ancienne note héritée)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_attente', to='port.escale'),
        ),
        migrations.AddIndex(
            model_name='noteattente',
            index=models.Index(fields=['navire', 'escale'], name='port_noteat_navire__364c13_idx'),
        ),
        migrations.AddIndex(
            model_name='noteattente',
            index=models.Index(fields=['archive'], name='port_noteat_archive_532bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='escale',
            index=models.Index(fields=['navire', 'active'], name='port_escale_navire__06467e_idx'),
        ),
        migrations.AddIndex(
            model_name='escale',
            index=models.Index(fields=['date_debut'], name='port_escale_date_de_75e941_idx'),
        ),
    ]
