# Generated by Django 6.0.3 on 2026-09-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0077_alter_noteattente_options_creneaureserve_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree_rade', 'Entrée en rade'), ('entree_quai', 'Entrée à quai'), ('sortie_quai', 'Sortie du quai'), ('sortie_port', 'Sortie du port'), ('changement_etat', "Changement d'état")], max_length=20)),
                ('etat_avant', models.CharField(blank=True, max_length=20)),
                ('etat_apres', models.CharField(blank=True, max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='scraping_auto', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='port.navire')),
                ('quai_apres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entree', to='port.quai')),
                ('quai_avant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortie', to='port.quai')),
            ],
            options={
                'verbose_name': 'Mouvement de navire',
                'verbose_name_plural': 'Mouvements de navires',
                'ordering': ['-date_detection'],
            },
        ),
    ]
