# Generated by Django 6.1.1 on 2026-09-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0078_mouvementnavire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationquai',
            name='agent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='affectationquai',
            name='entite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='navire',
            name='agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agent / Consignataire'),
        ),
        migrations.AlterField(
            model_name='navire',
            name='entite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entité exploitante'),
        ),
        migrations.AlterField(
            model_name='navire',
            name='marchandise_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
